require: rubocop-rspec

Rails:
  Enabled: true

Style/IndentationConsistency:
  EnforcedStyle: rails

AllCops:
  TargetRubyVersion: 2.4

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/AndOr:
  EnforcedStyle: conditionals

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/RedundantSelf:
  Enabled: false

Style/MutableConstant:
  Exclude:
    - "**/version.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
